### ISSUE TITLE
Requesting permission to add library for Particle devices

### ISSUE THREAD

**Issue by NGenetzky** [rjbatista/tm1638-library#42]
1. I have [forked this repository](https://github.com/NGenetzky/tm1638-library).
2. I have modified it to conform to Particle library requirements (on branch 'Particle/master'). I have attempted to retain all copyright and license information.

I would like to publically upload it to Particle to allow others to use the library.

**Comment by rjbatista** [comment]
Sure. I don't have any issue with this.
