### ISSUE TITLE
Read buttons via IRQ?

### ISSUE THREAD

**Issue by mickeyl** [rjbatista/tm1638-library#51]
Thanks for this great library. Among all those on the internet, it was the first one which immediately worked for me on an ESP32C6.

Since all examples are using polling to scan the button state, I wonder whether it's possible to be notified via IRQ when the button state changes or is it just not designed for that?

**Comment by maxint-rd** [comment]
The TM1638 has no interrupt pin, so it's indeed not designed to be used as such.

**Comment by mickeyl** [comment]
I was expecting that, thanks for clarifying.
